### ISSUE TITLE
Option to Sort Projects

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#17]
Would be handy to be able to sort projects Alphabetically, by Date Created and by Date Updated.

Definitely not critical.

**Comment by Charlie9830** [comment]
Agreed. I will add this into the Round 2 Release. Unfortunately, date created sorting for projects existing prior to round 2 release will still be semi random as I am not currently storing date created data.

**Comment by Charlie9830** [comment]
@RobH779 I will be interested in your opinion on the sort by updated setting once Round 2 release is out. In testing I have found it to be a bit annoying, it causes the projects to jump around a lot as they are re sorted live when you change something inside them. If you have multiple users using the same project this could mean you end up never able to easily spot the project you want to select.

It also puts extra stress on the Database quota, the DB is denormalized "flat" data. Meaning that inside the DB, Tasks and Tasklists aren't actually nested inside a project, they are stored in separate tables and only nested into eachother on the Client. This means that for example updating a task, now takes 2 writes to the DB rather than just one. If you think the feature doesn't have that much merit, I will disable it to save on DB transactions.

**Comment by RobH779** [comment]
@Charlie9830 Ah yeah of course. I definitely didn't consider multiple contributors to a project causing them to 'randomly' re-order themselves. I thought of it more as a way to keep your most used projects at the top and lesser used ones lower down automatically. 

Taking into consideration the additional DB transactions, I can see it potentially not being worth the trouble. Database transactions don't grow on trees after all.

Having said that I'll be interested to see if it does provide any conveniences to workflow or if it becomes an overbearing nuisance... as automation often does.
