### ISSUE TITLE
Colour picker erratic behaviour on Desktop

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#69]
**Describe the bug**
When using the colour picker in settings, dragging the cursor near the left or bottom edges of the gradient box causes jumping around inside the box.

**What were you doing at the time?**
Dragging the cursor up the left-most edge to select an appropriate grey colour. Doing this caused the colour picker to zoom around inside the box.

**Expected behavior**
I wold have expected the cursor to hit the far left edge and move only up and down, as it does on the right-most edge. Same goes for top and bottom.

**Version Information**
 - OS: MasOS 10.13.6
 - Version 2.0.3

**Comment by Charlie9830** [comment]
Good find. Happens on Windows as well. I suspect it is due to the popup loosing Mouse/Drag focus and reverting to some default value. I'll look at this in the next Hotfix.
Thanks for the report.

**Comment by Charlie9830** [comment]
So as far as I can tell, this is happening due to `tinycolor` which is is the library that `react-color` uses, which is the library I use to generate the Color Picker is doing an internal conversion to Hex Code. I may be completely off the mark here, but it seems that some values cannot be converted to Hex, so it coerces the value into one that can be expressed as Hex Code, which jumps the pointer to a different location. This occurs mostly at the bottom end of the Saturation spectrum (Left hand side of the color picker) and the bottom end of the Luminosity spectrum (Bottom of the color picker). 

In order to fix this I would have to open and Pull Request with `tinycolor` have that approved and merged in, then open a pull request with `react-color` and get that approved and merged in. Right now that is in the too hard basket.

I am going to close this issue and reopen a new one as a Feature request in the next Major release. I think a viable work around would be using the arrow keys to fine tune the color pointer location. I should be able to do this without messing around in libraries I don't have direct control over.
