### ISSUE TITLE
Localized Project Layout support

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#81]
**General Feedback**
Not really a bug, more of a feature request. Something I discovered today when introducing TJ Devine to the software is that if one user changes their Task List layout, it updates everyones!
We found this frustrating as we were continually 'battling' and changing around the layout to something that worked better for ourselves only to come back and find it had been changed again.

Wondering if it was possible to introduce separate layouts stored for each user on the same Project?

**Comment by Charlie9830** [comment]
That's an interesting point. Firstly though, the only thing that should be getting synced between devices is the size and position of each individual List. The size of the project as a whole should be irrelevant as it uses a system that is agnostic to the available space. In other words, re sizing the window, shouldn't cause someone else's layout to change, if it is doing that, then that is indeed a bug.

As for individual layout storage, from a technical stand point I see no reason why it shouldn't be possible. As for the User Experience, I would like to keep layouts synced  between users and devices as the default behavior, so that when new users are joining a project, they are immediately setup in a state that's ready to use, instead of having to create their own layout first. I will however look at implementing an option for users to localize their own copy of the layout to their own account on a project by project basis. 

I have assigned this to the next major feature release. That will come hopefully by the end of September.

**Comment by RobH779** [comment]
Yeah that does make sense. Adding someone to a Project and having them presented with some random default arrangement is somewhat unintuitive.
Opting in to individual layouts is a good solution to this.
